rmdir Animals\debug /s /q
rmdir Animals\Release /s /q
rmdir animation\debug /s /q
rmdir animation\Release /s /q
rmdir Artifact\debug /s /q
rmdir Artifact\Release /s /q
rmdir "BackgroundShipTask"\debug /s /q
rmdir "BackgroundShipTask"\Release /s /q
rmdir Ballsplash\debug /s /q
rmdir Ballsplash\Release /s /q
rmdir Battle_interface\debug /s /q
rmdir Battle_interface\Release /s /q
rmdir blade\debug /s /q
rmdir blade\Release /s /q
rmdir Blot\debug /s /q
rmdir Blot\Release /s /q
rmdir CameraDialog\debug /s /q
rmdir CameraDialog\Release /s /q
rmdir Collide\debug /s /q
rmdir Collide\Release /s /q
rmdir Common_h\debug /s /q
rmdir Common_h\Release /s /q
rmdir Dialog\debug /s /q
rmdir Dialog\Release /s /q
rmdir DX8RENDER\debug /s /q
rmdir DX8RENDER\Release /s /q
rmdir ENGINE\debug /s /q
rmdir ENGINE\Release /s /q
rmdir Gameutils\debug /s /q
rmdir Gameutils\Release /s /q
rmdir Geometry\debug /s /q
rmdir Geometry\Release /s /q
rmdir InterfaceEditor\debug /s /q
rmdir InterfaceEditor\Release /s /q
rmdir Island\debug /s /q
rmdir Island\Release /s /q
rmdir Lighter\debug /s /q
rmdir Lighter\Release /s /q
rmdir Location\debug /s /q
rmdir Location\Release /s /q
rmdir Locator\debug /s /q
rmdir Locator\Release /s /q
rmdir Mast\debug /s /q
rmdir Mast\Release /s /q
rmdir MasterServer\debug /s /q
rmdir MasterServer\Release /s /q
rmdir MLeaks\debug /s /q
rmdir MLeaks\Release /s /q
rmdir Model\debug /s /q
rmdir Model\Release /s /q
rmdir NET\debug /s /q
rmdir NET\Release /s /q
rmdir Particles\debug /s /q
rmdir Particles\Release /s /q
rmdir Pc_controls\debug /s /q
rmdir Pc_controls\Release /s /q
rmdir Pcs_controls\debug /s /q
rmdir Pcs_controls\Release /s /q
rmdir Peoples_on_ship\debug /s /q
rmdir Peoples_on_ship\Release /s /q
rmdir res\debug /s /q
rmdir res\Release /s /q
rmdir Rigging\debug /s /q
rmdir Rigging\Release /s /q
rmdir Sailors\debug /s /q
rmdir Sailors\Release /s /q
rmdir SCRIPT_LIBRIARY\debug /s /q
rmdir SCRIPT_LIBRIARY\Release /s /q
rmdir Sea\debug /s /q
rmdir Sea\Release /s /q
rmdir Sea_ai\debug /s /q
rmdir Sea_ai\Release /s /q
rmdir Sea_cameras\debug /s /q
rmdir Sea_cameras\Release /s /q
rmdir Sea_operator\debug /s /q
rmdir Sea_operator\Release /s /q
rmdir SeaCreatures\debug /s /q
rmdir SeaCreatures\Release /s /q
rmdir Seafoam\debug /s /q
rmdir Seafoam\Release /s /q
rmdir Setup\debug /s /q
rmdir Setup\Release /s /q
rmdir shadow\debug /s /q
rmdir shadow\Release /s /q
rmdir Ship\debug /s /q
rmdir Ship\Release /s /q
rmdir Sink_effect\debug /s /q
rmdir Sink_effect\Release /s /q
rmdir Sound\debug /s /q
rmdir Sound\Release /s /q
rmdir SoundService\debug /s /q
rmdir SoundService\Release /s /q
rmdir Teleport\debug /s /q
rmdir Teleport\Release /s /q
rmdir Telescope\debug /s /q
rmdir Telescope\Release /s /q
rmdir Tornado\debug /s /q
rmdir Tornado\Release /s /q
rmdir Touch\debug /s /q
rmdir Touch\Release /s /q
rmdir WaterRings\debug /s /q
rmdir WaterRings\Release /s /q
rmdir Weather\debug /s /q
rmdir Weather\Release /s /q
rmdir Worldmap\debug /s /q
rmdir Worldmap\Release /s /q
rmdir Xinterface\debug /s /q
rmdir Xinterface\Release /s /q
pause




