
#################
###  ZLIB
#################
set(CONAN_ZLIB_ROOT_RELEASE "C:/Users/Greentwip/.conan/data/zlib/1.2.11/_/_/package/3fb49604f9c2f729b85ba3115852006824e72cab")
set(CONAN_INCLUDE_DIRS_ZLIB_RELEASE "C:/Users/Greentwip/.conan/data/zlib/1.2.11/_/_/package/3fb49604f9c2f729b85ba3115852006824e72cab/include")
set(CONAN_LIB_DIRS_ZLIB_RELEASE "C:/Users/Greentwip/.conan/data/zlib/1.2.11/_/_/package/3fb49604f9c2f729b85ba3115852006824e72cab/lib")
set(CONAN_BIN_DIRS_ZLIB_RELEASE )
set(CONAN_RES_DIRS_ZLIB_RELEASE )
set(CONAN_SRC_DIRS_ZLIB_RELEASE )
set(CONAN_BUILD_DIRS_ZLIB_RELEASE "C:/Users/Greentwip/.conan/data/zlib/1.2.11/_/_/package/3fb49604f9c2f729b85ba3115852006824e72cab/")
set(CONAN_FRAMEWORK_DIRS_ZLIB_RELEASE )
set(CONAN_LIBS_ZLIB_RELEASE zlib)
set(CONAN_PKG_LIBS_ZLIB_RELEASE zlib)
set(CONAN_SYSTEM_LIBS_ZLIB_RELEASE )
set(CONAN_FRAMEWORKS_ZLIB_RELEASE )
set(CONAN_FRAMEWORKS_FOUND_ZLIB_RELEASE "")  # Will be filled later
set(CONAN_DEFINES_ZLIB_RELEASE )
set(CONAN_BUILD_MODULES_PATHS_ZLIB_RELEASE )
# COMPILE_DEFINITIONS are equal to CONAN_DEFINES without -D, for targets
set(CONAN_COMPILE_DEFINITIONS_ZLIB_RELEASE )

set(CONAN_C_FLAGS_ZLIB_RELEASE "")
set(CONAN_CXX_FLAGS_ZLIB_RELEASE "")
set(CONAN_SHARED_LINKER_FLAGS_ZLIB_RELEASE "")
set(CONAN_EXE_LINKER_FLAGS_ZLIB_RELEASE "")

# For modern cmake targets we use the list variables (separated with ;)
set(CONAN_C_FLAGS_ZLIB_RELEASE_LIST "")
set(CONAN_CXX_FLAGS_ZLIB_RELEASE_LIST "")
set(CONAN_SHARED_LINKER_FLAGS_ZLIB_RELEASE_LIST "")
set(CONAN_EXE_LINKER_FLAGS_ZLIB_RELEASE_LIST "")

# Apple Frameworks
conan_find_apple_frameworks(CONAN_FRAMEWORKS_FOUND_ZLIB_RELEASE "${CONAN_FRAMEWORKS_ZLIB_RELEASE}" "_ZLIB" "_RELEASE")
# Append to aggregated values variable
set(CONAN_LIBS_ZLIB_RELEASE ${CONAN_PKG_LIBS_ZLIB_RELEASE} ${CONAN_SYSTEM_LIBS_ZLIB_RELEASE} ${CONAN_FRAMEWORKS_FOUND_ZLIB_RELEASE})


#################
###  SPDLOG
#################
set(CONAN_SPDLOG_ROOT_RELEASE "C:/Users/Greentwip/.conan/data/spdlog/1.8.2/_/_/package/5f068d3b65ebc5bb906d7ad2d998a4a2f8ad5db4")
set(CONAN_INCLUDE_DIRS_SPDLOG_RELEASE "C:/Users/Greentwip/.conan/data/spdlog/1.8.2/_/_/package/5f068d3b65ebc5bb906d7ad2d998a4a2f8ad5db4/include")
set(CONAN_LIB_DIRS_SPDLOG_RELEASE "C:/Users/Greentwip/.conan/data/spdlog/1.8.2/_/_/package/5f068d3b65ebc5bb906d7ad2d998a4a2f8ad5db4/lib")
set(CONAN_BIN_DIRS_SPDLOG_RELEASE )
set(CONAN_RES_DIRS_SPDLOG_RELEASE )
set(CONAN_SRC_DIRS_SPDLOG_RELEASE )
set(CONAN_BUILD_DIRS_SPDLOG_RELEASE "C:/Users/Greentwip/.conan/data/spdlog/1.8.2/_/_/package/5f068d3b65ebc5bb906d7ad2d998a4a2f8ad5db4/")
set(CONAN_FRAMEWORK_DIRS_SPDLOG_RELEASE )
set(CONAN_LIBS_SPDLOG_RELEASE spdlog)
set(CONAN_PKG_LIBS_SPDLOG_RELEASE spdlog)
set(CONAN_SYSTEM_LIBS_SPDLOG_RELEASE )
set(CONAN_FRAMEWORKS_SPDLOG_RELEASE )
set(CONAN_FRAMEWORKS_FOUND_SPDLOG_RELEASE "")  # Will be filled later
set(CONAN_DEFINES_SPDLOG_RELEASE "-DSPDLOG_COMPILED_LIB"
			"-DSPDLOG_FMT_EXTERNAL")
set(CONAN_BUILD_MODULES_PATHS_SPDLOG_RELEASE )
# COMPILE_DEFINITIONS are equal to CONAN_DEFINES without -D, for targets
set(CONAN_COMPILE_DEFINITIONS_SPDLOG_RELEASE "SPDLOG_COMPILED_LIB"
			"SPDLOG_FMT_EXTERNAL")

set(CONAN_C_FLAGS_SPDLOG_RELEASE "")
set(CONAN_CXX_FLAGS_SPDLOG_RELEASE "")
set(CONAN_SHARED_LINKER_FLAGS_SPDLOG_RELEASE "")
set(CONAN_EXE_LINKER_FLAGS_SPDLOG_RELEASE "")

# For modern cmake targets we use the list variables (separated with ;)
set(CONAN_C_FLAGS_SPDLOG_RELEASE_LIST "")
set(CONAN_CXX_FLAGS_SPDLOG_RELEASE_LIST "")
set(CONAN_SHARED_LINKER_FLAGS_SPDLOG_RELEASE_LIST "")
set(CONAN_EXE_LINKER_FLAGS_SPDLOG_RELEASE_LIST "")

# Apple Frameworks
conan_find_apple_frameworks(CONAN_FRAMEWORKS_FOUND_SPDLOG_RELEASE "${CONAN_FRAMEWORKS_SPDLOG_RELEASE}" "_SPDLOG" "_RELEASE")
# Append to aggregated values variable
set(CONAN_LIBS_SPDLOG_RELEASE ${CONAN_PKG_LIBS_SPDLOG_RELEASE} ${CONAN_SYSTEM_LIBS_SPDLOG_RELEASE} ${CONAN_FRAMEWORKS_FOUND_SPDLOG_RELEASE})


#################
###  FMT
#################
set(CONAN_FMT_ROOT_RELEASE "C:/Users/Greentwip/.conan/data/fmt/7.1.2/_/_/package/3fb49604f9c2f729b85ba3115852006824e72cab")
set(CONAN_INCLUDE_DIRS_FMT_RELEASE "C:/Users/Greentwip/.conan/data/fmt/7.1.2/_/_/package/3fb49604f9c2f729b85ba3115852006824e72cab/include")
set(CONAN_LIB_DIRS_FMT_RELEASE "C:/Users/Greentwip/.conan/data/fmt/7.1.2/_/_/package/3fb49604f9c2f729b85ba3115852006824e72cab/lib")
set(CONAN_BIN_DIRS_FMT_RELEASE )
set(CONAN_RES_DIRS_FMT_RELEASE )
set(CONAN_SRC_DIRS_FMT_RELEASE )
set(CONAN_BUILD_DIRS_FMT_RELEASE "C:/Users/Greentwip/.conan/data/fmt/7.1.2/_/_/package/3fb49604f9c2f729b85ba3115852006824e72cab/")
set(CONAN_FRAMEWORK_DIRS_FMT_RELEASE )
set(CONAN_LIBS_FMT_RELEASE fmt)
set(CONAN_PKG_LIBS_FMT_RELEASE fmt)
set(CONAN_SYSTEM_LIBS_FMT_RELEASE )
set(CONAN_FRAMEWORKS_FMT_RELEASE )
set(CONAN_FRAMEWORKS_FOUND_FMT_RELEASE "")  # Will be filled later
set(CONAN_DEFINES_FMT_RELEASE )
set(CONAN_BUILD_MODULES_PATHS_FMT_RELEASE )
# COMPILE_DEFINITIONS are equal to CONAN_DEFINES without -D, for targets
set(CONAN_COMPILE_DEFINITIONS_FMT_RELEASE )

set(CONAN_C_FLAGS_FMT_RELEASE "")
set(CONAN_CXX_FLAGS_FMT_RELEASE "")
set(CONAN_SHARED_LINKER_FLAGS_FMT_RELEASE "")
set(CONAN_EXE_LINKER_FLAGS_FMT_RELEASE "")

# For modern cmake targets we use the list variables (separated with ;)
set(CONAN_C_FLAGS_FMT_RELEASE_LIST "")
set(CONAN_CXX_FLAGS_FMT_RELEASE_LIST "")
set(CONAN_SHARED_LINKER_FLAGS_FMT_RELEASE_LIST "")
set(CONAN_EXE_LINKER_FLAGS_FMT_RELEASE_LIST "")

# Apple Frameworks
conan_find_apple_frameworks(CONAN_FRAMEWORKS_FOUND_FMT_RELEASE "${CONAN_FRAMEWORKS_FMT_RELEASE}" "_FMT" "_RELEASE")
# Append to aggregated values variable
set(CONAN_LIBS_FMT_RELEASE ${CONAN_PKG_LIBS_FMT_RELEASE} ${CONAN_SYSTEM_LIBS_FMT_RELEASE} ${CONAN_FRAMEWORKS_FOUND_FMT_RELEASE})


### Definition of global aggregated variables ###

set(CONAN_DEPENDENCIES_RELEASE zlib spdlog fmt)

set(CONAN_INCLUDE_DIRS_RELEASE "C:/Users/Greentwip/.conan/data/zlib/1.2.11/_/_/package/3fb49604f9c2f729b85ba3115852006824e72cab/include"
			"C:/Users/Greentwip/.conan/data/spdlog/1.8.2/_/_/package/5f068d3b65ebc5bb906d7ad2d998a4a2f8ad5db4/include"
			"C:/Users/Greentwip/.conan/data/fmt/7.1.2/_/_/package/3fb49604f9c2f729b85ba3115852006824e72cab/include" ${CONAN_INCLUDE_DIRS_RELEASE})
set(CONAN_LIB_DIRS_RELEASE "C:/Users/Greentwip/.conan/data/zlib/1.2.11/_/_/package/3fb49604f9c2f729b85ba3115852006824e72cab/lib"
			"C:/Users/Greentwip/.conan/data/spdlog/1.8.2/_/_/package/5f068d3b65ebc5bb906d7ad2d998a4a2f8ad5db4/lib"
			"C:/Users/Greentwip/.conan/data/fmt/7.1.2/_/_/package/3fb49604f9c2f729b85ba3115852006824e72cab/lib" ${CONAN_LIB_DIRS_RELEASE})
set(CONAN_BIN_DIRS_RELEASE  ${CONAN_BIN_DIRS_RELEASE})
set(CONAN_RES_DIRS_RELEASE  ${CONAN_RES_DIRS_RELEASE})
set(CONAN_FRAMEWORK_DIRS_RELEASE  ${CONAN_FRAMEWORK_DIRS_RELEASE})
set(CONAN_LIBS_RELEASE zlib spdlog fmt ${CONAN_LIBS_RELEASE})
set(CONAN_PKG_LIBS_RELEASE zlib spdlog fmt ${CONAN_PKG_LIBS_RELEASE})
set(CONAN_SYSTEM_LIBS_RELEASE  ${CONAN_SYSTEM_LIBS_RELEASE})
set(CONAN_FRAMEWORKS_RELEASE  ${CONAN_FRAMEWORKS_RELEASE})
set(CONAN_FRAMEWORKS_FOUND_RELEASE "")  # Will be filled later
set(CONAN_DEFINES_RELEASE "-DSPDLOG_COMPILED_LIB"
			"-DSPDLOG_FMT_EXTERNAL" ${CONAN_DEFINES_RELEASE})
set(CONAN_BUILD_MODULES_PATHS_RELEASE  ${CONAN_BUILD_MODULES_PATHS_RELEASE})
set(CONAN_CMAKE_MODULE_PATH_RELEASE "C:/Users/Greentwip/.conan/data/zlib/1.2.11/_/_/package/3fb49604f9c2f729b85ba3115852006824e72cab/"
			"C:/Users/Greentwip/.conan/data/spdlog/1.8.2/_/_/package/5f068d3b65ebc5bb906d7ad2d998a4a2f8ad5db4/"
			"C:/Users/Greentwip/.conan/data/fmt/7.1.2/_/_/package/3fb49604f9c2f729b85ba3115852006824e72cab/" ${CONAN_CMAKE_MODULE_PATH_RELEASE})

set(CONAN_CXX_FLAGS_RELEASE " ${CONAN_CXX_FLAGS_RELEASE}")
set(CONAN_SHARED_LINKER_FLAGS_RELEASE " ${CONAN_SHARED_LINKER_FLAGS_RELEASE}")
set(CONAN_EXE_LINKER_FLAGS_RELEASE " ${CONAN_EXE_LINKER_FLAGS_RELEASE}")
set(CONAN_C_FLAGS_RELEASE " ${CONAN_C_FLAGS_RELEASE}")

# Apple Frameworks
conan_find_apple_frameworks(CONAN_FRAMEWORKS_FOUND_RELEASE "${CONAN_FRAMEWORKS_RELEASE}" "" "_RELEASE")
# Append to aggregated values variable: Use CONAN_LIBS instead of CONAN_PKG_LIBS to include user appended vars
set(CONAN_LIBS_RELEASE ${CONAN_LIBS_RELEASE} ${CONAN_SYSTEM_LIBS_RELEASE} ${CONAN_FRAMEWORKS_FOUND_RELEASE})
