#ifndef COMMON_LAYER_HPP
#define COMMON_LAYER_HPP

#define EXECUTE 0
#define REALIZE 1
#define SEA_EXECUTE 2
#define SEA_REALIZE 3
#define INTERFACE_EXECUTE 4
#define INTERFACE_REALIZE 5
#define FADER_EXECUTE 6
#define FADER_REALIZE 7
#define LIGHTER_EXECUTE 8
#define LIGHTER_REALIZE 9
#define VIDEO_EXECUTE 10
#define VIDEO_REALIZE 11
#define EDITOR_REALIZE 12
#define INFO_REALIZE 13
#define SOUND_DEBUG_REALIZE 14
#define SEA_REFLECTION 15
#define SEA_REFLECTION2 16
#define SEA_SUNROAD 17
#define SUN_TRACE 18
#define SAILS_TRACE 19
#define HULL_TRACE 20
#define MAST_ISLAND_TRACE 21
#define MAST_SHIP_TRACE 22
#define SHIP_CANNON_TRACE 23
#define FORT_CANNON_TRACE 24
#define ISLAND_TRACE 25
#define SHADOW 26
#define BLOOD 27
#define RAIN_DROPS 28

#endif
