#include "flag.h"
#include "rope.h"
#include "sail.h"
#include "script_func.h"
#include "vant.h"

INTERFACE_FUNCTION
CREATE_CLASS(SAIL)
CREATE_CLASS(FLAG)
CREATE_CLASS(ROPE)
CREATE_CLASS(VANT)
CREATE_CLASS(VANTL)
CREATE_CLASS(VANTZ)
CREATE_SCRIPTLIBRIARY(SCRIPT_RIGGING_FILES)
