#define MAX_ENCOUNTER_TYPES			20

// Encounters types

#define ENCOUNTER_TYPE_MERCHANT_SMALL				0
#define ENCOUNTER_TYPE_MERCHANT_MEDIUM				1
#define ENCOUNTER_TYPE_MERCHANT_LARGE				2

#define ENCOUNTER_TYPE_MERCHANT_GUARD_SMALL			3
#define ENCOUNTER_TYPE_MERCHANT_GUARD_MEDIUM		4
#define ENCOUNTER_TYPE_MERCHANT_GUARD_LARGE			5

#define ENCOUNTER_TYPE_ESCORT_SMALL					6
#define ENCOUNTER_TYPE_ESCORT_MEDIUM				7
#define ENCOUNTER_TYPE_ESCORT_LARGE					8

#define ENCOUNTER_TYPE_PATROL_SMALL					9
#define ENCOUNTER_TYPE_PATROL_MEDIUM				10
#define ENCOUNTER_TYPE_PATROL_LARGE					11

#define ENCOUNTER_TYPE_PIRATE_SMALL					12
#define ENCOUNTER_TYPE_PIRATE_MEDIUM				13
#define ENCOUNTER_TYPE_PIRATE_LARGE					14

#define ENCOUNTER_TYPE_SQUADRON						15
#define ENCOUNTER_TYPE_FLEET						16
#define ENCOUNTER_TYPE_ARMADA						17

#define ENCOUNTER_TYPE_PUNITIVE_SQUADRON			18

#define ENCOUNTER_TYPE_ALONE						19


// Encounter type
#define ENCOUNTER_TRADE				0
#define ENCOUNTER_WAR				1

object EncountersTypes[MAX_ENCOUNTER_TYPES];
