#pragma once

#define EMISSION_RATE "Emission rate"
#define MAX_PARTICLES_COUNT "Max Particles count"
#define PARTICLE_LIFE_TIME "Life time"
#define PARTICLE_MASS "Mass"
#define PARTICLE_SPIN "Spin"
#define PARTICLE_VELOCITY_POWER "Velocity"
#define EMITTER_POSITION "Position"
#define EMISSION_DIR_X "Physics Dir X"
#define EMISSION_DIR_Y "Physics Dir Y"
#define EMISSION_DIR_Z "Physics Dir Z"
#define PARTICLE_SPIN_DRAG "Spin Friction"
#define PARTICLE_SIZE "Size"
#define PARTICLE_ANIMFRAME "Animation frame"
#define PARTICLE_COLOR "Color"
#define EMITTER_LIFETIME "Life time"
#define PARTICLE_FRAMES "Texture"
#define PARTICLE_TRANSPARENCY "Transparency"
#define EMITTER_LOOPING "Looping"
#define PARTICLE_DRAG "Friction"
#define PARTICLE_TRACK_X "Track X"
#define PARTICLE_TRACK_Y "Track Y"
#define PARTICLE_TRACK_Z "Track Z"
#define PARTICLE_PHYSIC_BLEND "Physic blend"
#define ATTACHEDEMITTER_NAME "Attached emitter"
#define EMITTER_NAME "Name"
#define PARTICLE_SPIN_DRAGX "Spin Friction X"
#define PARTICLE_SPIN_DRAGY "Spin Friction Y"
#define PARTICLE_SPIN_DRAGZ "Spin Friction Z"
#define PARTICLE_SPIN_X "Spin X"
#define PARTICLE_SPIN_Y "Spin Y"
#define PARTICLE_SPIN_Z "Spin Z"
#define PARTICLE_GEOM_NAMES "Model names"
#define PARTICLE_NAME "Name"
#define PARTICLE_EMISSION_RATE "Emission rate"
#define PARTICLE_MAX_COUNT "Max Particles count"
#define PARTICLE_GRAVITATION_K "ForceField_gravity"
#define PARTICLE_DIR_ORIENT "Direction Orient"
#define PARTICLE_ADDPOWER "Add Technique Power"
