name: CI Windows

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'tools/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'tools/**'
      - '*.md'

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'same_content'
          do_not_skip: '["pull_request", "release", "workflow_dispatch", "schedule"]'

  build-windows:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        configuration: [debug, release]
    name: 'Windows [${{ matrix.configuration }}]'
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Install Conan
      run: pip install conan==1.59.0
    - name: Configure and build
      uses: lukka/run-cmake@v10
      with:
        configurePreset: default
        buildPreset: '${{ matrix.configuration }}'
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: storm-engine.${{ matrix.configuration }}
        path: build/default/${{ matrix.configuration }}

permissions: write-all
